version: '3'

services:
    xornet-haproxy:
        image: haproxy
        restart: unless-stopped
        ports:
            - "7000:7000"
        volumes:
            - ./haproxy:/usr/local/etc/haproxy
    xornet-redis:
        image: redis
        restart: unless-stopped
        ports:
            - "6379:6379"
    xornet-backend-1:
        image: xornet-backend
        restart: unless-stopped
        environment:
            - SHARD_ID=1
    xornet-backend-2:
        image: xornet-backend
        restart: unless-stopped
        environment:
            - SHARD_ID=2
    xornet-backend-3:
        image: xornet-backend
        restart: unless-stopped
        environment:
            - SHARD_ID=3
    xornet-backend-4:
        image: xornet-backend
        restart: unless-stopped
        environment:
            - SHARD_ID=4
    xornet-backend-5:
        image: xornet-backend
        restart: unless-stopped
        environment:
            - SHARD_ID=5
    xornet-backend-6:
        image: xornet-backend
        restart: unless-stopped
        environment:
            - SHARD_ID=6
    xornet-backend-7:
        image: xornet-backend
        restart: unless-stopped
        environment:
            - SHARD_ID=7
    xornet-backend-8:
        image: xornet-backend
        restart: unless-stopped
        environment:
            - SHARD_ID=8