version: '3'

services:
    xornet-haproxy:
        image: haproxy
        restart: unless-stopped
        ports:
            - "7000:7000"
        volumes:
            - ./haproxy:/usr/local/etc/haproxy
    xornet-redis:
        image: redis
        restart: unless-stopped
        ports:
            - "6379:6379"
    xornet-backend-1:
        image: xornet-backend
        restart: unless-stopped
        environment:
            - SHARD_ID=1
    xornet-backend-2:
        image: xornet-backend
        restart: unless-stopped
        environment:
            - SHARD_ID=2
    xornet-backend-3:
        image: xornet-backend
        restart: unless-stopped
        environment:
            - SHARD_ID=3
    xornet-backend-4:
        image: xornet-backend
        restart: unless-stopped
        environment:
            - SHARD_ID=4
    xornet-backend-5:
        image: xornet-backend
        restart: unless-stopped
        environment:
            - SHARD_ID=5
    xornet-backend-6:
        image: xornet-backend
        restart: unless-stopped
        environment:
            - SHARD_ID=6
    xornet-backend-7:
        image: xornet-backend
        restart: unless-stopped
        environment:
            - SHARD_ID=7
    xornet-backend-8:
        image: xornet-backend
        restart: unless-stopped
        environment:
            - SHARD_ID=8
    xornet-backend-9:
        image: xornet-backend
        restart: unless-stopped
        environment:
            - SHARD_ID=9
    xornet-backend-10:
        image: xornet-backend
        restart: unless-stopped
        environment:
            - SHARD_ID=10
    xornet-backend-11:
        image: xornet-backend
        restart: unless-stopped
        environment:
            - SHARD_ID=11
    xornet-backend-12:
        image: xornet-backend
        restart: unless-stopped
        environment:
            - SHARD_ID=12
    xornet-backend-13:
        image: xornet-backend
        restart: unless-stopped
        environment:
            - SHARD_ID=13
    xornet-backend-14:
        image: xornet-backend
        restart: unless-stopped
        environment:
            - SHARD_ID=14
    xornet-backend-15:
        image: xornet-backend
        restart: unless-stopped
        environment:
            - SHARD_ID=15
    xornet-backend-16:
        image: xornet-backend
        restart: unless-stopped
        environment:
            - SHARD_ID=16
    xornet-backend-17:
        image: xornet-backend
        restart: unless-stopped
        environment:
            - SHARD_ID=17
    xornet-backend-18:
        image: xornet-backend
        restart: unless-stopped
        environment:
            - SHARD_ID=18
    xornet-backend-19:
        image: xornet-backend
        restart: unless-stopped
        environment:
            - SHARD_ID=19
    xornet-backend-20:
        image: xornet-backend
        restart: unless-stopped
        environment:
            - SHARD_ID=20
    xornet-backend-21:
        image: xornet-backend
        restart: unless-stopped
        environment:
            - SHARD_ID=21
    xornet-backend-22:
        image: xornet-backend
        restart: unless-stopped
        environment:
            - SHARD_ID=22
    xornet-backend-23:
        image: xornet-backend
        restart: unless-stopped
        environment:
            - SHARD_ID=23
    xornet-backend-24:
        image: xornet-backend
        restart: unless-stopped
        environment:
            - SHARD_ID=24
    xornet-backend-25:
        image: xornet-backend
        restart: unless-stopped
        environment:
            - SHARD_ID=25
    xornet-backend-26:
        image: xornet-backend
        restart: unless-stopped
        environment:
            - SHARD_ID=26
    xornet-backend-27:
        image: xornet-backend
        restart: unless-stopped
        environment:
            - SHARD_ID=27
    xornet-backend-28:
        image: xornet-backend
        restart: unless-stopped
        environment:
            - SHARD_ID=28
    xornet-backend-29:
        image: xornet-backend
        restart: unless-stopped
        environment:
            - SHARD_ID=29
    xornet-backend-30:
        image: xornet-backend
        restart: unless-stopped
        environment:
            - SHARD_ID=30
    xornet-backend-31:
        image: xornet-backend
        restart: unless-stopped
        environment:
            - SHARD_ID=31
    xornet-backend-32:
        image: xornet-backend
        restart: unless-stopped
        environment:
            - SHARD_ID=32
