name: Build Xornet Server

on: [push, pull_request, workflow_dispatch]

env:
  CARGO_TERM_COLOR: always

jobs:
  compile-linux:
    strategy:
      fail-fast: true
      matrix: 
        targetArch:
          - 386
          - amd64
          - arm
          - mips
          - mips64
          - mips64le
          - mipsle
          - s390x
    runs-on: ubuntu-latest
    name: "Compile for Linux"
    steps: 
      - name: 🛎 Checkout
        uses: actions/checkout@v2
      - name: ⚡ Set Version Variable
        id: version
        run: >
          echo "::set-output name=value::$(cat ./version.txt)"
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.4
        with:
          go-version: '^1.17.1'
      - name: Install Gox
        run: go get github.com/mitchellh/gox
      - name: Compile 
        run: gox -os="linux" -arch="${{matrix.targetArch}}" -output="./dist/xornet_server_${{ steps.version.outputs.value }}_{{.OS}}_{{.Arch}}"
      - name: 💎 Upload Builds
        uses: actions/upload-artifact@v1
        with:
          name: xornet_server__${{ steps.version.outputs.value }}_linux_${{matrix.targetArch}}
          path: dist/xornet_server_${{ steps.version.outputs.value }}_linux_${{matrix.targetArch}}

  compile-freebsd:
    strategy:
      fail-fast: true
      matrix: 
        targetArch:
          - 386
          - amd64
          - arm
    runs-on: ubuntu-latest
    name: "Compile for FreeBSD"
    steps: 
      - name: 🛎 Checkout
        uses: actions/checkout@v2
      - name: ⚡ Set Version Variable
        id: version
        run: >
          echo "::set-output name=value::$(cat ./version.txt)"
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.4
        with:
          go-version: '^1.17.1'
      - name: Install Gox
        run: go get github.com/mitchellh/gox
      - name: Compile 
        run: gox -os="freebsd" -arch="${{matrix.targetArch}}" -output="./dist/xornet_server_${{ steps.version.outputs.value }}_{{.OS}}_{{.Arch}}"
      - name: 💎 Upload Builds
        uses: actions/upload-artifact@v1
        with:
          name: xornet_server__${{ steps.version.outputs.value }}_freebsd_${{matrix.targetArch}}
          path: dist/xornet_server_${{ steps.version.outputs.value }}_freebsd_${{matrix.targetArch}}

  compile-netbsd:
    strategy:
      fail-fast: true
      matrix: 
        targetArch:
          - 386
          - amd64
          - arm
    runs-on: ubuntu-latest
    name: "Compile for NetBSD"
    steps: 
      - name: 🛎 Checkout
        uses: actions/checkout@v2
      - name: ⚡ Set Version Variable
        id: version
        run: >
          echo "::set-output name=value::$(cat ./version.txt)"
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.4
        with:
          go-version: '^1.17.1'
      - name: Install Gox
        run: go get github.com/mitchellh/gox
      - name: Compile 
        run: gox -os="netbsd" -arch="${{matrix.targetArch}}" -output="./dist/xornet_server_${{ steps.version.outputs.value }}_{{.OS}}_{{.Arch}}"
      - name: 💎 Upload Builds
        uses: actions/upload-artifact@v1
        with:
          name: xornet_server__${{ steps.version.outputs.value }}_netbsd_${{matrix.targetArch}}
          path: dist/xornet_server_${{ steps.version.outputs.value }}_netbsd_${{matrix.targetArch}}

  compile-openbsd:
    strategy:
      fail-fast: true
      matrix: 
        targetArch:
          - 386
          - amd64
    runs-on: ubuntu-latest
    name: "Compile for OpenBSD"
    steps: 
      - name: 🛎 Checkout
        uses: actions/checkout@v2
      - name: ⚡ Set Version Variable
        id: version
        run: >
          echo "::set-output name=value::$(cat ./version.txt)"
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.4
        with:
          go-version: '^1.17.1'
      - name: Install Gox
        run: go get github.com/mitchellh/gox
      - name: Compile 
        run: gox -os="openbsd" -arch="${{matrix.targetArch}}" -output="./dist/xornet_server_${{ steps.version.outputs.value }}_{{.OS}}_{{.Arch}}"
      - name: 💎 Upload Builds
        uses: actions/upload-artifact@v1
        with:
          name: xornet_server__${{ steps.version.outputs.value }}_openbsd_${{matrix.targetArch}}
          path: dist/xornet_server_${{ steps.version.outputs.value }}_openbsd_${{matrix.targetArch}}
  compile-windows:
    strategy:
      fail-fast: true
      matrix: 
        targetArch:
          - 386
          - amd64
    runs-on: ubuntu-latest
    name: "Compile for Windows"
    steps: 
      - name: 🛎 Checkout
        uses: actions/checkout@v2
      - name: ⚡ Set Version Variable
        id: version
        run: >
          echo "::set-output name=value::$(cat ./version.txt)"
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.4
        with:
          go-version: '^1.17.1'
      - name: Install Gox
        run: go get github.com/mitchellh/gox
      - name: Compile 
        run: gox -os="windows" -arch="${{matrix.targetArch}}" -output="./dist/xornet_server_${{ steps.version.outputs.value }}_{{.OS}}_{{.Arch}}"
      - name: 💎 Upload Builds
        uses: actions/upload-artifact@v1
        with:
          name: xornet_server__${{ steps.version.outputs.value }}_windows_${{matrix.targetArch}}
          path: dist/xornet_server_${{ steps.version.outputs.value }}_windows_${{matrix.targetArch}}.exe

  compile-darwin:
    runs-on: ubuntu-latest
    name: "Compile for Darwin (amd64)"
    steps: 
      - name: 🛎 Checkout
        uses: actions/checkout@v2
      - name: ⚡ Set Version Variable
        id: version
        run: >
          echo "::set-output name=value::$(cat ./version.txt)"
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.4
        with:
          go-version: '^1.17.1'
      - name: Install Gox
        run: go get github.com/mitchellh/gox
      - name: Compile 
        run: gox -os="darwin" -arch="amd64" -output="./dist/xornet_server_${{ steps.version.outputs.value }}_{{.OS}}_{{.Arch}}"
      - name: 💎 Upload Builds
        uses: actions/upload-artifact@v1
        with:
          name: xornet_server__${{ steps.version.outputs.value }}_darwin_amd64
          path: dist/xornet_server_${{ steps.version.outputs.value }}_darwin_amd64
